---

securityContext:
  runAsUser: null

podSecurityContext:
  fsGroup: null
  runAsUser: null

sysctlInitContainer:
  enabled: false

esConfig:
 elasticsearch.yml: |
   xpack.monitoring.collection.enabled: true

