FROM docker.elastic.co/logstash/logstash:7.17.1
RUN bin/logstash-plugin install logstash-output-syslog
RUN bin/logstash-plugin install logstash-output-rsyslog
RUN bin/logstash-plugin install logstash-filter-kv
RUN bin/logstash-plugin install logstash-filter-json
RUN bin/logstash-plugin install logstash-filter-split
RUN bin/logstash-plugin install logstash-output-gelfFROM docker.elastic.co/logstash/logstash:7.17.1
RUN bin/logstash-plugin install logstash-output-syslog
RUN bin/logstash-plugin install logstash-output-rsyslog
RUN bin/logstash-plugin install logstash-filter-kv
RUN bin/logstash-plugin install logstash-filter-json
RUN bin/logstash-plugin install logstash-filter-split
RUN bin/logstash-plugin install logstash-output-gelf
